name: PUBLISH TO STAGE
on:
  push:
    branches: [ stage ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ngcobalt326.manitu.net
        username: ftp200009065
        password: ${{ secrets.ftp_password }}
