# Unfortunately this workflow is pushing git internal folders to the webhost! Currently not ready for prime time.
on: push
name: FTP UPLOAD WITH HASH
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Publish
      uses: socram8888/ftp-hash-sync@v1
      with:
        host: ngcobalt326.manitu.net
        username: ftp200008953
        password: ${{ secrets.FTP_PASSWORD }}
